import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { Backdrop, CircularProgress } from "@mui/material";
import { useRecoilValue } from "recoil";

import RootWorkspace from "../container/RootWorkspace";
import { workspacesState } from "../recoil/atom/workspace";
import { TWorkspace, TWorkspaces } from "../recoil/atom/workspace/types";

const Home: NextPage = () => {
  const { push: routerPush } = useRouter();
  const w: TWorkspaces = useRecoilValue(workspacesState);

  useEffect(() => {
    if (w.fetched) {
      if (
        w?.workspaces?.current_workspace_id &&
        w?.workspaces?.current_workspace_id !== ""
      ) {
        routerPush(`/workspace/${w.workspaces.current_workspace_id}`);
        return;
      }
      if (
        w.workspaces &&
        w.workspaces.workspaces &&
        w.workspaces.workspaces.length > 0
      ) {
        const ws: TWorkspace = w.workspaces.workspaces[0];
        if (ws) {
          routerPush(`/workspace/${ws.workspace_id}`);
          return;
        }
      }
      routerPush(`/workspace/`);
    }
  }, [routerPush, w]);

  return (
    <RootWorkspace>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Backdrop
        sx={{ color: "#fff", zIndex: (theme) => theme.zIndex.drawer + 1 }}
        open
      >
        <CircularProgress />
      </Backdrop>
    </RootWorkspace>
  );
};

export default Home;
