apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "40"
  labels:
    app: hxb-next-webui
    component: microservice
  name: hxb-next-webui
  namespace: default
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hxb-next-webui
      component: microservice
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hxb-next-webui
        component: microservice
      name: hxb-next-webui
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: hxb-next-webui-config
        image: beee/hxb-next-webui:57edd3941f82362b939b0a9c28db04945a1aed54
        imagePullPolicy: Always
        name: beee-hxb-next-webui
        ports:
        - containerPort: 3000
          name: hxb-next-webui
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: hxb-next-webui
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 70m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: app
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
